### ISSUE TITLE
requiring "Generate Test Coverage Files" and/or "Instrument Program Flow" causes Console spam

### ISSUE THREAD

**Issue by jmoody** [specta/specta#167] opened 2015-06-22 19:21 UTC
I have recently upgraded to Specta 1.0.2 which required that I set the following flags in the Build Settings of the app under test:

```
GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
GCC_GENERATE_TEST_COVERAGE_FILES=YES
```

Now my console log is filled with messages like this:

```
profiling: /Users/moody/Library/Developer/Xcode/DerivedData/sso-authorizations-embfxpdxuvewkmdvtuwwasxnizxk/Build/Intermediates/sso-authorization.build/Release-iphonesimulator/XCTest.build/Objects-normal/i386/CalUserManagerTest.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /Users/moody/Library/Developer/Xcode/DerivedData/sso-authorizations-embfxpdxuvewkmdvtuwwasxnizxk/Build/Intermediates/sso-authorization.build/Release-iphonesimulator/XCTest.build/Objects-normal/i386/CalUserManagerTest.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000001)
profiling: /Users/moody/Library/Developer/Xcode/DerivedData/sso-authorizations-embfxpdxuvewkmdvtuwwasxnizxk/Build/Intermediates/sso-authorization.build/Release-iphonesimulator/XCTest.build/Objects-normal/i386/CalUserManagerTest.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /Users/moody/Library/Developer/Xcode/DerivedData/sso-authorizations-embfxpdxuvewkmdvtuwwasxnizxk/Build/Intermediates/sso-authorization.build/Release-iphonesimulator/XCTest.build/Objects-normal/i386/CalUserManagerTest.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /Users/moody/Library/Developer/Xcode/DerivedData/sso-authorizations-embfxpdxuvewkmdvtuwwasxnizxk/Build/Intermediates/sso-authorization.build/Release-iphonesimulator/XCTest.build/Objects-normal/i386/CalUserManagerTest.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /Users/moody/Library/Developer/Xcode/DerivedData/sso-authorizations-embfxpdxuvewkmdvtuwwasxnizxk/Build/Intermediates/sso-authorization.build/Release-iphonesimulator/XCTest.build/Objects-normal/i386/CalUserManagerTest.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /Users/moody/Library/Developer/Xcode/DerivedData/sso-authorizations-embfxpdxuvewkmdvtuwwasxnizxk/Build/Intermediates/sso-authorization.build/Release-iphonesimulator/XCTest.build/Objects-normal/i386/CalUserManagerTest.gcda: cannot merge previous GCDA file: pt arc tag (0x00000000)
profiling: /Users/moody/Library/Developer/Xcode/DerivedData/sso-authorizations-embfxpdxuvewkmdvtuwwasxnizxk/Build/Intermediates/sso-authorization.build/Release-iphonesimulator/XCTest.build/Objects-normal/i386/CalUserManagerTest.gcda: cannot merge previous run count: corrupt object tag (0x00000000)
```

Why are these two flags required?  And what can be done about the spam?  Cleaning the project works for one run, but the next time I run the tests, they are back.

**Comment by jmoody** [comment] 2015-07-16 16:10
As a temporary solution, I add this Run Script Build Phase script to my XCTest target _before_ compilation.

```
INTERMEDIATES_DIR="${BUILD_DIR}/../Intermediates"
 
if [ -e "${INTERMEDIATES_DIR}" ]; then
  find ${INTERMEDIATES_DIR} -type f -name "*.gcda" -exec rm -rf {} \;
fi
```

**Comment by Goles** [comment] 2015-09-14 21:41
Does Specta support coverage reports with Xcode @jmoody ?

**Comment by Goles** [comment] 2015-09-14 22:08
Does Specta support coverage reports with Xcode @jmoody ?

That didn't really remove the console spam in my case though :( 

cc @orta

**Comment by jmoody** [comment] 2015-09-15 07:14
@Goles I have no idea.

**Comment by Goles** [comment] 2015-09-15 07:31
I actually opened a radar: on this... I think it might be an Xcode bug

**Comment by orta** [comment] 2015-09-15 13:21
TBH, the build setting could probably be removed from Specta and sent in via the CI commend, which is how we do it [at Artsy](https://github.com/artsy/energy/blob/master/Makefile#L43).

**Comment by paweldudek** [comment] 2015-09-16 11:38
@orta :+1:, we're doing the same thing.

**Comment by Goles** [comment] 2015-09-16 16:26
@orta what build setting are you talking about?

**Comment by orta** [comment] 2015-09-16 17:25
specifically adding `GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES` to the `xcodebuild` command

**Comment by Goles** [comment] 2015-09-16 18:27
That's interesting, maybe that will do the trick

**Comment by apphipster** [comment] 2015-10-02 20:45
I have spent some time trying to figure out how to get rid of those ugly and annoying messages:

profiling: /Users/appfactory/Desktop/WORK/App/trunk/ObjectiveC.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)

It seemed like an Xcode 7 issue that was not fixed in the current Xcode 7.1 beta 2.
The problem is caused by failing to merge the existing .gcda coverage files with the current results.

What I tried:
Remove those .gcda files with RunScript	 - does not work in my case
echo "Delete .gcda files"
echo "${OBJECT_FILE_DIR_normal}/${CURRENT_ARCH}"

Attention: the ObjectiveC.gcda file may be at a different location!

Set the following build settings to YES - also not helping
Enable Code Coverage Support to YES 
Generate Legacy Test Coverage Files to YES 
Instrument Program Flow to YES

The solution in my case:
Set the following build settings for the main target
Enable Code Coverage Support to YES 
Generate Legacy Test Coverage Files to YES 
Instrument Program Flow to NO

Set the following build settings for the test target (and any other targets)
Enable Code Coverage Support to NO 
Generate Legacy Test Coverage Files to NO 
Instrument Program Flow to NO

Hope it helps!

**Comment by jmoody** [comment] 2015-10-05 10:41
@apphipster Thanks for investigating.  I will give it a try.

To the original question: **Why are these two flags required?**

Are these flags necessary?

**Comment by liuslevis** [comment] 2015-12-05 03:54
guess it's a xcode 7.1 bug. ref: http://davidlau.me/2015/12/05/Trying-to-fix-Xcode-7-GDCA-file-corruption/

**Comment by dbarden** [comment] 2015-12-11 04:59
This ticket can now be closed

**Closed** 2015-12-11 10:04 UTC

**Comment by jmenezes** [comment] 2015-12-14 09:51
To resolve the issue of getting "cannot merge previous GCDA file: corrupt arc tag" messages in console, avoid generating ObjectiveC.gcda file, by making “Enable Modules (C and Objective-C)" setting to "NO", in the target settings.

**Comment by Ad1991** [comment] 2016-01-18 14:29
@jmenezes `@import` statements would not work if you set that flag to NO. Not something I would like to do.
