### ISSUE TITLE
v0.3.0.beta1 not reporting the results in the test navigator in xcode 6

### ISSUE THREAD

**Issue by brianblanchard-wf** [specta/specta#108] opened 2014-10-08 21:20 UTC
When I run my unit tests using specta `v0.3.0.beta` in `Xcode 6`, I see the tests executing in the tests in the test navigator within xcode like so:

![screen shot 2014-10-08 at 1 57 44 pm](https://cloud.githubusercontent.com/assets/1747583/4567283/be1bfb34-4f2f-11e4-8b50-69d39533dc10.png)

but when the tests are finished running the test navigator does not show the results of the test run like so:

![screen shot 2014-10-08 at 1 57 47 pm](https://cloud.githubusercontent.com/assets/1747583/4567301/e6de010c-4f2f-11e4-88aa-48dd1b299470.png)

As you can see, I have 8 failing tests but I cannot tell which ones have failed easily in the test navigator on the left side of Xcode, I have to sift through all the logs.

Are you guys aware of this issue? If you are aware of the issue, how can it be resolved?

Any help is greatly appreciated! Thanks!

**Setup:**
`Xcode: 6.0.1`
`Specta: 0.3.0.beta1`
`Expecta: 0.3.1`
`OCMock: 3.1.0`

**Comment by orta** [comment] 2015-02-10 22:57
closing as a dupe of #85 - this seems to be based on the phase of the moon and how strong venus' pull is.

**Closed by orta** 2015-02-10 22:57 UTC
