### ISSUE TITLE
Carthage Binaries

### ISSUE THREAD

**Issue by Autoc0diq** [specta/specta#192] opened 2015-10-21 20:39 UTC
Would it be possible to add binaries to your releases? This would speed up our build time. Thanks!

**Comment by orta** [comment] 2015-10-22 06:33
This is a duplicate of #187

**Closed by orta** 2015-10-22 06:33 UTC

**Comment by robb** [comment] 2015-10-22 07:40
FWIW, I'd be looking into committing frameworks with git lfs now.

**Comment by Autoc0diq** [comment] 2015-10-22 16:35
Is it supported by Carthage?

-s

**Comment by robb** [comment] 2015-10-23 11:58
Checking in `Carthage/Build` should do the trick I reckon
