### ISSUE TITLE
v0.3.0 beta report spt_runExampleAtIndex for all test case in test navigation bar.

### ISSUE THREAD

**Issue by PhucDuy** [specta/specta#117] opened 2014-11-28 16:49 UTC
I use specta v0.3.1 in Xcode 6.1 (6A1052d). After I run my test, test navigation show this results.
![screen shot 2014-11-28 at 11 42 01 pm](https://cloud.githubusercontent.com/assets/6514068/5230397/56a76e1a-7758-11e4-983f-196fb036a50a.png)
I already set an environment variable named SPECTA_REPORTER_CLASS to SPTXCTestReporter in my test scheme. but I didn't work.
How can I get results in my test report?

**Comment by esttorhe** [comment] 2015-01-14 22:58
Just to add more to this issue; I tried with custom class and the issue is still present :x:

**Comment by fatuhoku** [comment] 2015-01-23 14:53
+1 
![screen shot 2015-01-23 at 14 53 03](https://cloud.githubusercontent.com/assets/430233/5876493/8b56e004-a30f-11e4-9051-e9205d1c331a.png) same situation  on AppCode, unsurprisingly.

**Comment by orta** [comment] 2015-02-10 21:41
Any ideas on this? I've not seen this in a long time

![screen shot 2015-02-10 at 4 40 36 pm](https://cloud.githubusercontent.com/assets/49038/6137027/9d7703d0-b143-11e4-85f9-f0643fd4be4f.png)

**Comment by orta** [comment] 2015-02-10 21:49
closing as a dupe of https://github.com/specta/specta/issues/85 - which has more info

**Closed by orta** 2015-02-10 21:49 UTC
